name: CI

on: [push, pull_request]

jobs:
  tests:
    name: "Tests (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.71.2
          cache: true
          environments: dev

      - name: Check formatting and lint
        run: pixi run check-fmt

      - name: Run unit tests
        run: pixi run test-ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
